---
title: "Learning_Progress"
author: "GeoClark"
output: html_document
---
# 2021 Learning
After years of working on proprietary projects for my employer I created this Git profile to share my projects and track my progress as I develop my core competencies. 

  [Rmarkdown tips](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf?_ga=2.260928973.1332295168.1611943840-241221221.1611943840)

 [Rstudio_cheatsheets](https://rstudio.com/resources/cheatsheets/)



### Pending Reading and Projects

* Introduction to Statistical Learning in R (February to present) [PDF_LINK](https://static1.squarespace.com/static/5ff2adbe3fe4fe33db902812/t/601cc86d7f828c4792e0bcae/1612499080032/ISLR+Seventh+Printing.pdf)
* Practical Data Science with R by Nina Zumel
* Learning Python by Mark Lutz
* Introduction to machine learning with Python by Guido and Mueller
* Hands-on Machine Learning with Scikit-Learn, Keras & TensorFlow by Aurelion Geron
* R reticulate package [reticulate](https://rstudio.github.io/reticulate/articles/calling_python.html)
* Kaggle Datasets
* Plot Amarylis dataset
* Create bread making dataset
* add template for plotting azimuthal data on a Rose Plot.

### Completed Training (Fall 2020 Onward)
  * *Introduction to Machine Learning in R* by Scott Burger (completed March 2021)

  * *Effective Data Storytelling* by Brent Dykes (completed Feb 2021)
  * *Handbook of Regression Modeling in People Analytics* by Keith McNulty (completed Feb 2021)
  * Data Camp (Nov-Dec 2020)
    + Introduction to writing function in R 
    + Exploratory data analysis in R
    + Importing and Cleaning data in R
    + Intermediate visualization with ggplot
    + Introduction to visualization with ggplot
    + Intermediate data importing
    + Introduction to importing data
    + Joining data with Dplyr
    + Data Manipulation with Dplyr
    + Introduction to Tidyverse
    + Intermediate R
    + Introduction to R


#### Things I googled


* Data_Wrangling
  + [TidyVerse](https://dplyr.tidyverse.org/index.html)
  
* ggplot
  + [basics](http://www.sthda.com/english/wiki/ggplot2-essentials)
  + [geom_ribbons](https://ggplot2.tidyverse.org/reference/geom_ribbon.html)

* Handy Links
  + [R_for_Data_Science](https://r4ds.had.co.nz/index.html)

* Statistics in R
  + [DataFlair](https://data-flair.training/blogs/machine-learning-for-r-programming/)

